"""add deck_intelligence column

Revision ID: 21645bf3e465
Revises: 7b93202a65aa
Create Date: 2026-05-07 00:50:30.633742

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '21645bf3e465'
down_revision: Union[str, None] = '7b93202a65aa'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('decks', sa.Column('deck_intelligence', sa.JSON(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('decks', 'deck_intelligence')
    # ### end Alembic commands ###
