"""add deck preferences column

Revision ID: 6097a4163a16
Revises: afcad8aff461
Create Date: 2026-04-26 17:50:11.818511

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '6097a4163a16'
down_revision: Union[str, None] = 'afcad8aff461'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('decks', sa.Column('preferences', sa.JSON(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('decks', 'preferences')
    # ### end Alembic commands ###
