"""add notes and ai_context to deck_cards

Revision ID: 7b93202a65aa
Revises: 6097a4163a16
Create Date: 2026-04-28 17:15:37.854269

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '7b93202a65aa'
down_revision: Union[str, None] = '6097a4163a16'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('deck_cards', sa.Column('notes', sa.Text(), nullable=True))
    op.add_column('deck_cards', sa.Column('ai_context', postgresql.JSON(astext_type=sa.Text()), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('deck_cards', 'ai_context')
    op.drop_column('deck_cards', 'notes')
    # ### end Alembic commands ###
