"""add_cards_table_with_vector

Revision ID: 9f63afbaf3b4
Revises: a1f44badd08f
Create Date: 2026-05-20 20:23:20.738337

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import pgvector.sqlalchemy


# revision identifiers, used by Alembic.
revision: str = '9f63afbaf3b4'
down_revision: Union[str, None] = 'a1f44badd08f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('cards',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('scryfall_id', sa.String(), nullable=False),
    sa.Column('oracle_id', sa.String(), nullable=True),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('type_line', sa.String(), nullable=True),
    sa.Column('oracle_text', sa.Text(), nullable=True),
    sa.Column('mana_cost', sa.String(), nullable=True),
    sa.Column('cmc', sa.Float(), nullable=True),
    sa.Column('colors', sa.JSON(), nullable=True),
    sa.Column('color_identity', sa.JSON(), nullable=True),
    sa.Column('legalities', sa.JSON(), nullable=True),
    sa.Column('prices', sa.JSON(), nullable=True),
    sa.Column('image_uris', sa.JSON(), nullable=True),
    sa.Column('power', sa.String(), nullable=True),
    sa.Column('toughness', sa.String(), nullable=True),
    sa.Column('rarity', sa.String(), nullable=True),
    sa.Column('set_code', sa.String(), nullable=True),
    sa.Column('keywords', sa.JSON(), nullable=True),
    sa.Column('roles', sa.JSON(), nullable=True),
    sa.Column('archetypes', sa.JSON(), nullable=True),
    sa.Column('search_terms', sa.JSON(), nullable=True),
    sa.Column('synergies', sa.JSON(), nullable=True),
    sa.Column('power_level', sa.String(), nullable=True),
    sa.Column('strategic_summary', sa.Text(), nullable=True),
    sa.Column('embedding', pgvector.sqlalchemy.vector.VECTOR(dim=1536), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_cards_name'), 'cards', ['name'], unique=False)
    op.create_index(op.f('ix_cards_oracle_id'), 'cards', ['oracle_id'], unique=False)
    op.create_index(op.f('ix_cards_scryfall_id'), 'cards', ['scryfall_id'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_cards_scryfall_id'), table_name='cards')
    op.drop_index(op.f('ix_cards_oracle_id'), table_name='cards')
    op.drop_index(op.f('ix_cards_name'), table_name='cards')
    op.drop_table('cards')
    # ### end Alembic commands ###
