"""add_deck_versions_table

Revision ID: a1f44badd08f
Revises: 7164a5455947
Create Date: 2026-05-15 20:45:56.975769

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a1f44badd08f'
down_revision: Union[str, None] = '7164a5455947'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
"""add_deck_versions_table

Revision ID: a1f44badd08f
Revises: 7164a5455947
Create Date: 2026-05-15 20:45:56.975769
"""
from typing import Sequence, Union
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects.postgresql import UUID

revision: str = 'a1f44badd08f'
down_revision: Union[str, None] = '7164a5455947'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    op.create_table(
        'deck_versions',
        sa.Column('id', UUID(as_uuid=True), primary_key=True),
        sa.Column('deck_id', UUID(as_uuid=True), sa.ForeignKey('decks.id', ondelete='CASCADE'), nullable=False),
        sa.Column('version_number', sa.Integer(), nullable=False),
        sa.Column('name', sa.String(), nullable=True),
        sa.Column('card_snapshot', sa.JSON(), nullable=False),
        sa.Column('analytics_snapshot', sa.JSON(), nullable=True),
        sa.Column('strategy_snapshot', sa.JSON(), nullable=True),
        sa.Column('created_at', sa.DateTime(), server_default=sa.func.now()),
    )


def downgrade() -> None:
    op.drop_table('deck_versions')

def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
