"""add strategy_profile to decks

Revision ID: afcad8aff461
Revises: 4a42c037ade8
Create Date: 2026-04-18 16:43:39.533403

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'afcad8aff461'
down_revision: Union[str, None] = '4a42c037ade8'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('decks', sa.Column('strategy_profile', sa.JSON(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('decks', 'strategy_profile')
    # ### end Alembic commands ###
