"""add_edhrec_rank_to_cards

Revision ID: b544fbe38a01
Revises: 9f63afbaf3b4
Create Date: 2026-05-23 20:11:48.916948

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b544fbe38a01'
down_revision: Union[str, None] = '9f63afbaf3b4'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('cards', sa.Column('edhrec_rank', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('cards', 'edhrec_rank')
    # ### end Alembic commands ###
